name: cafe_restaurant_app
description: A restaurant management application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  intl: ^0.19.0
  fl_chart: ^0.66.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  geolocator: ^10.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - mobil_uygulama_resimleri/